export const animations = new Map([
    ['0', require('../assets/numbers/00.json')],
    ['1', require('../assets/numbers/01.json')],
    ['2', require('../assets/numbers/02.json')],
    ['3', require('../assets/numbers/03.json')],
    ['4', require('../assets/numbers/04.json')],
    ['5', require('../assets/numbers/05.json')],
    ['6', require('../assets/numbers/06.json')],
    ['7', require('../assets/numbers/07.json')],
    ['8', require('../assets/numbers/08.json')],
    ['9', require('../assets/numbers/09.json')],
    ['10', require('../assets/numbers/10.json')],
    ['11', require('../assets/numbers/11.json')],
    ['12', require('../assets/numbers/12.json')],
    ['13', require('../assets/numbers/12+.json')],
    ['14', require('../assets/numbers/12+.json')],
    ['15', require('../assets/numbers/12+.json')],
    ['16', require('../assets/numbers/12+.json')],
    ['17', require('../assets/numbers/12+.json')],
    ['18', require('../assets/numbers/12+.json')],
]);
